### ISSUE TITLE
Create Licensing and copyright page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#16] opened 2020-05-18 12:33 UTC
- [x] Create page 
- [x] Add description of what is being covered (include difference between article and asset level licensing)
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by naushinthomson** [comment] 2020-09-25 12:17
@FAtherden-eLife @bcollins14 @Melissa37 @JGilbert-eLife 

This [page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/licensing-and-copyright) is now ready for review!
A few notes for @FAtherden-eLife 
The text of permissions-info is currently 'This article is licensed under aXXXXXX license. XXXXXX' - there should be a space between a and XXXXXX. I've updated this in the gitbook page but the schematron needs to be updated. 
Similarly, the text of permissions-parent has a misspelling of 'allowed'. 
The text of fig-permissions-test-13 refers to the ali:licens_ref element but should this be spelled an ali:license_ref?

I'm also unsure of what action to provide for fig-permissions-test-13 so would appreciate help with that!

**Comment by Melissa37** [comment] 2020-09-25 14:31
>The license of the article will be captured in the underlying XML (see here) and a copyright statement will be present in the article PDF.

Suggest change to:
The license of the article will be captured in the underlying XML (see here and here).
A copyright statement will be present for CC BY content but not for CC0 content.

where the second here is to a CC0 version.

Perhaps the PDF example should two samples, one of CCBY and the other of CC0.

**Comment by Melissa37** [comment] 2020-09-25 14:33
>The editorial team check figure permissions as part of submission quality checks. They will leave a note for Exeter if permissions information needs to be added to the XML.


Suggest adding:

But production is the backstop in this process and may need to veto previous decisions or double-check the communication and decision-making process.

**Comment by Melissa37** [comment] 2020-09-25 14:35
>If an article has reproduced figures from content that was previously published under a CC BY (2, 3 or 4) or CC0 license, that content must be properly attributed and credited

I think you can remove CC0 from here as it can be used freely with no restrictions? Maybe it's just common politeness to do it?!

**Comment by Melissa37** [comment] 2020-09-25 14:36
>If the article license is CC0 but the reproduced figure is CC BY, this needs to be indicated in the underlying XML as the authors/creators still retain copyright of the original figure. For example:

Suggest changing to:
If the article license is CC0 but the reproduced figure is CC BY, this needs to be indicated in the underlying XML as the authors/creators/publisher still retain copyright of the original figure. For example:

Smetimes publishers are still retaining copy right :-(

**Comment by Melissa37** [comment] 2020-09-25 14:39
>If authors chose to exactly reproduce a figure or panel from a previously published, non-open access/non-CC BY 2, 3, or 4 article

I'd ditch the non-open access bit as open access can mean different things to different people and it's more about the license than anything else. EG if a piece of content is free on a journal website because the publisher has opened it, they can close it again at will. That is not open access, but someone might think it is because it is free (right now).

**Comment by Melissa37** [comment] 2020-09-25 14:43
>If authors chose to exactly reproduce a figure or panel from a previously published, non-open access/non-CC BY 2, 3, or 4 article in part or in whole, it will need to be published under a separate license. This is because the original content will have been published under a license that retains copyright. An article published in Nature, for example, will be copyright to the Nature Publishing Group, and articles published in Science will be copyright to the American Association for the Advancement of Science and so on. For eLife to reproduce the content, it must be made clear that the original publisher retains copyright, and it is not covered by the CC BY or CC0 license that applies to the rest of the eLife article. The same issue applies when authors incorporate images from other copyrighted media into their figures (e.g. film stills or artwork). The authors will need to confirm they have permission from the copyright holders to reproduce the figure or figure panel and state what has been reproduced in the legend. A permissions statement will also need to be added in the XML with the license details for the reproduced image. The permissions text may have been provided already as part of the figure or figure supplement legend. If so, it should be removed and moved into the permissions tagging.

I don't think it's the copyright (CCBY has copy right) it's about it being "all rights reserved" or not falling under a specific machine-readable license. Many of these publishers have weird and wonderful licensing that is specific to them and available as a page on their website. Sorry, it's all very confusing - I think this section could probably do with a collective rewrite on the next production call :-)

**Comment by Melissa37** [comment] 2020-09-25 14:46
>If the note from editorial says a figure does not require permissions, these should still be checked. If it is not possible to check (because the figure is from a book for example), this doesn't need to be followed up further. However, where possible, figure permissions should be double-checked regardless of what the note says.

I don't think the book is a good example as many books are online, I'd say because it is behind access controls - but then that means it's pretty dodgy that we don't need permission!

**Comment by Melissa37** [comment] 2020-09-25 14:49
>Error: permissions must contain copyright-statement.
Action: This error will fire if the permissions wrapper for an article does not have a copyright-statement element. The copyright statement is made up of the copyright symbol © followed by the copyright year, and the copyright holder. Exeter will need to add this, for example:<copyright-statement>© 2019, Smith et al</copyright-statement>
See an example of XML for the article-level license here. 

CC0 does not need a copyright statement so I assume it only fires for those that require this

**Comment by Melissa37** [comment] 2020-09-25 14:50
>permissions-test-3
Error: permissions must contain copyright-holder.
Action: This error will fire if there is no copyright holder for an article.

add, if a copyright holder is required (ie not required for CC0)

**Comment by Melissa37** [comment] 2020-09-25 14:52
>permissions-test-4
Error: permissions must contain an ali:free_to_read element.
Action: This error will fire if there is no ali:free_to_read element in the permissions wrapper. This will need to be added by Exeter. See an example of XML for the article-level license here.

Only required for CC licenses so this is not quite true. 

This error will fire if there is no ali:free_to_read element in the permissions wrapper and one is required

**Comment by Melissa37** [comment] 2020-09-25 14:53
>Error: permissions must contain license.
Action: This error will fire if there is no license element in the permissions wrapper. This will need to be added by Exeter. The license element contains information about which CC license the article is published under. See an example of XML for the article-level license here.

@FAtherden-eLife is this about license-p?

**Comment by Melissa37** [comment] 2020-09-25 14:54
>Action: This error will fire if the copyright year does not match the published date of the article (for example, if an article was published in 2020 but the copyright year is 2019). This will need to be corrected by Exeter. See an example of XML for the article-level license here.

Suggest changing to:

>Action: This error will fire if the copyright year for the article does not match the published date of the article (for example, if an article was published in 2020 but the copyright year is 2019). This will need to be corrected by Exeter. See an example of XML for the article-level license here.

**Comment by Melissa37** [comment] 2020-09-25 14:55
>permissions-test-7
Error: copyright-holder is incorrect. If the article has one author then it should be their surname. If it has two authors it should be the surname of the first, then ' and ' and then the surname of the second. If three or more, it should be the surname of the first, and then ' et al'. Currently it's XXXXXX
Action: This error will fire if the copyright holder is incorrect. 

suggest change

>Action: This error will fire if the copyright holder is incorrect. 

to 
Action: This error will fire if the copyright holder for the article is incorrect.

**Comment by Melissa37** [comment] 2020-09-25 14:56
>permissions-test-8
Error: copyright-statement must contain a concatenation of '© ', copyright-year, and copyright-holder. Currently it is XXXXXX when according to the other values it should be XXXXXX
Action: This error will fire if the copyright statement is incorrect. The copyright statement must be made up of the copyright symbol © followed by the correct copyright year, and the correct copyright holder (e.g. © 2019, Smith et al). This test checks whether the contents of the copyright statement match the values indicated in the copyright year and copyright holder fields. If any of these are incorrect, they will need to be fixed by Exeter. 

This only applies to the article level permissions doesn't it? I think we've had more in asset level permission statements?

@FAtherden-eLife

**Comment by Melissa37** [comment] 2020-09-25 14:56
>permissions-test-9
Error: license does not have an @xlink:href which is equal to 'http://creativecommons.org/publicdomain/zero/1.0/' or 'http://creativecommons.org/licenses/by/4.0/'.
Action: This error will fire if the license element has a link other than 'http://creativecommons.org/publicdomain/zero/1.0/' or 'http://creativecommons.org/licenses/by/4.0/'. This will need to be corrected by Exeter. 

Need to indicate this is article level and not asset level

**Comment by Melissa37** [comment] 2020-09-25 14:57
>license-test-1
Error: license must contain ali:license_ref.
Action: This error will fire if there is no ali:license_ref element in the license element. This element includes an appropriate creative commons link depending on which license the article will be published under. Exeter will need to add this. See an example of XML for the article-level license here.

Is this article level only or asset level too if it is CC?

@FAtherden-eLife

**Comment by Melissa37** [comment] 2020-09-25 14:58
>license-test-2
Error: license must contain one and only one license-p.
Action: This error will fire if the license for the article contains none or more than one license-p element. The license-p element includes a copyright statement, for example:
This article is distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use and redistribution provided that the original author and source are credited.
See an example of XML for the article-level license here. Exeter will need to correct this and include a link to the appropriate creative commons link depending on which license the article will be published under.

In this instance, I think it applies to article level and asset level!

**Comment by Melissa37** [comment] 2020-09-25 14:58
>reproduce-test-1
Warning: The caption for XXXXXX contains the text 'reproduced from', but has no permissions. Is this correct?
Action: This warning will appear if a figure caption includes the text 'reproduced from' but there is no permissions information tagged in the XML. If no notes have been left about permissions information to add, query the Production team who will discuss it with the Editorial team. See more about this here.

Is it limited to figures @FAtherden-eLife or does it apply to other assets too?

**Comment by Melissa37** [comment] 2020-09-25 14:59
reproduce-test-1 to reproduce-test-8

These all apply to all assets and not just figs?

**Comment by Melissa37** [comment] 2020-09-25 15:03
>fig-permissions-test-5
Error: permissions for XXXXXX has XXXXXX <copyright-statement> elements, when there can only be 0 or 1.
Action: This will appear if a permissions statement has more than 1 <copyright-statement> element. If the contents of these elements are the same, delete the duplicates. If they are different, double-check what the correct statement should be by comparing with the instructions given by the Production team

There should never be 2 statements?

**Comment by Melissa37** [comment] 2020-09-25 15:05
Thanks Naushin!

**Comment by FAtherden-eLife** [comment] 2020-09-29 11:18
> The text of permissions-info is currently 'This article is licensed under aXXXXXX license. XXXXXX' - there should be a space between a and XXXXXX. I've updated this in the gitbook page but the schematron needs to be updated.

Thanks. The Schematron doesn't need updating. That text is generated and if it's an unknown license then it will say 'an unknown license' at the end. If it's a known license then the space will be generated before the appropriate text (e.g. ' CC BY 4.0'). This is the reason there's no space between the text and the bit that generates that XXXXXX text.

**Comment by FAtherden-eLife** [comment] 2020-09-29 11:19
> Similarly, the text of permissions-parent has a misspelling of 'allowed'.
> The text of fig-permissions-test-13 refers to the ali:licens_ref element but should this be spelled an ali:license_ref?

Thanks - will update

**Comment by FAtherden-eLife** [comment] 2020-09-29 11:24
> I'm also unsure of what action to provide for fig-permissions-test-13 so would appreciate help with that!

As I recall this is a warning, not because there is a case where it would be appropriate to not have an `ali:license_ref` element when there is a CC type license, but rather because implementing this in Kriya has been a bit on and off. I recall Exeter (at some point) saying this would need development work in Kriya 1.5, but then there have also been cases recently where Exeter have added this in.

**Comment by FAtherden-eLife** [comment] 2020-09-29 11:25
>> Error: permissions must contain license.
>> Action: This error will fire if there is no license element in the permissions wrapper. This will need to be added by Exeter. The license element contains information about which CC license the article is published under. See an example of XML for the article-level license here.

> @FAtherden-eLife is this about license-p?

It's about the `<license>` element (the parent of `license-p`).

**Comment by FAtherden-eLife** [comment] 2020-09-29 13:34
>> permissions-test-8
>> Error: copyright-statement must contain a concatenation of '© ', copyright-year, and copyright-holder. Currently it is XXXXXX when according to the other values it should be XXXXXX
Action: This error will fire if the copyright statement is incorrect. The copyright statement must be made up of the copyright symbol © followed by the correct copyright year, and the correct copyright holder (e.g. © 2019, Smith et al). This test checks whether the contents of the copyright statement match the values indicated in the copyright year and copyright holder fields. If any of these are incorrect, they will need to be fixed by Exeter.

> This only applies to the article level permissions doesn't it? I think we've had more in asset level permission statements?

> @FAtherden-eLife

Yup, only article level. I can create a test for asset level licensing as well if sensible.

**Comment by FAtherden-eLife** [comment] 2020-09-29 13:36
>> license-test-1
>> Error: license must contain ali:license_ref.
>> Action: This error will fire if there is no ali:license_ref element in the license element. This element includes an appropriate creative commons link depending on which license the article will be published under. Exeter will need to add this. See an example of XML for the article-level license here.

> Is this article level only or asset level too if it is CC?

> @FAtherden-eLife

@Melissa37, this is just article level. `fig-permissions-test-13` covers the asset level equivalent.

**Comment by FAtherden-eLife** [comment] 2020-09-29 13:38
>> reproduce-test-1
>> Warning: The caption for XXXXXX contains the text 'reproduced from', but has no permissions. Is this correct?
>> Action: This warning will appear if a figure caption includes the text 'reproduced from' but there is no permissions information tagged in the XML. If no notes have been left about permissions information to add, query the Production team who will discuss it with the Editorial team. See more about this here.

> Is it limited to figures @FAtherden-eLife or does it apply to other assets too?

@Melissa37, figures and videos. I can expand it to other items (supp files and tables) but they're less commonly taken from elsewhere in our content. Would it be worth doing?

**Comment by FAtherden-eLife** [comment] 2020-09-29 13:38
> reproduce-test-1 to reproduce-test-8

> These all apply to all assets and not just figs?

As above, currently figures and videos

**Comment by FAtherden-eLife** [comment] 2020-09-29 13:41
>> fig-permissions-test-5
>> Error: permissions for XXXXXX has XXXXXX elements, when there can only be 0 or 1.
>> Action: This will appear if a permissions statement has more than 1 element. If the contents of these elements are the same, delete the duplicates. If they are different, double-check what the correct statement should be by comparing with the instructions given by the Production team

> There should never be 2 statements?

> And the same for fig-permissions-test-6 - 8

One statement per `<permissions>`. If there are multiple different permissions within a figure, then we're using multiple `<permissions>` each with only 1 of each of the required elements.

**Comment by FAtherden-eLife** [comment] 2020-09-29 13:46
> Adapted figures

I think we ourselves should avoid using the term adapted (unless referring to how authors describe to this stuff) and stick to redrawn or reproduced, since it presents a clear dichotomy for us.

**Comment by FAtherden-eLife** [comment] 2020-09-29 16:14
As @Melissa37 alludes to above, it's probably worth changing 'figure caption' in the actions for `reproduce-test-1`-`8` to asset caption.

**Comment by FAtherden-eLife** [comment] 2020-09-29 16:17
Thanks @naushinthomson. Nothing further from me.

**Comment by JGilbert-eLife** [comment] 2020-10-13 13:34
I'm not sure this makes sense? "A copyright statement will be present for CC BY content but not for CC0 content in the article PDF." At least not with the captions of the screenshots that follow. Technically, isn't it still a copyright statement if it states there is no copyright?

**Comment by JGilbert-eLife** [comment] 2020-10-13 13:38
Maybe change "which applies to the whole article including all assets." to "which by default applies to the whole article including all assets." I think that might fit better with the later sections.

**Comment by JGilbert-eLife** [comment] 2020-10-13 13:43
"Where assets are adapted or reproduced from previously published content, additional information may need to be added in the underlying XML." Is it worth leading with something like, "they may need to be exempted from the article-level license, with the details included in the underlying XML."

**Comment by JGilbert-eLife** [comment] 2020-10-13 13:44
For "Figures and figure supplements (or panels within these)" I'd suggest "Figures and figure supplements (in part or in whole)"

**Comment by JGilbert-eLife** [comment] 2020-10-13 13:56
"If so, it should be removed and moved into the permissions tagging."
I think this can be simplified to
"If so, it should be moved into the permissions tagging."
but I defer to your judgement!

**Comment by JGilbert-eLife** [comment] 2020-10-13 13:57
"If the note from editorial says a figure does not require permissions, these should still be checked."

Who does this checking?

**Comment by JGilbert-eLife** [comment] 2020-10-13 14:02
permissions-parent - isn't that structure?

**Comment by JGilbert-eLife** [comment] 2020-10-13 14:03
test-permissions-presence - likewise?

**Comment by JGilbert-eLife** [comment] 2020-10-13 14:09
permissions-test-4 - "This error will fire if there is no ali:free_to_read element in the permissions wrapper and one is required (i.e. does not apply to CC-BY articles)."

I'm afraid I don't quite understand what's being described here. Don't all our articles have this because we're open access?

**Comment by JGilbert-eLife** [comment] 2020-10-13 14:17
I think some of the links are still pointing to the figures page, as I assume the text was originally on this page. Alternatively, I may have fluffed them up while trying to use the links (sorry!).

**Comment by JGilbert-eLife** [comment] 2020-10-13 14:24
I wonder if it would be a good idea to give an example or two for fig-permissions-test-12, just to make sure it's clear what someone would be looking at if they encounter this.

**Comment by JGilbert-eLife** [comment] 2020-10-13 14:27
I slightly adjusted the XML layout for easier reading - tricky to judge this when it slides!

Otherwise - looks good, thanks @naushinthomson !

**Comment by bcollins14** [comment] 2020-10-15 13:15
Nothing more to add as I am not too clued up on the technical parts of this page but it read well to me, thanks!

**Comment by naushinthomson** [comment] 2020-11-25 10:17
@FAtherden-eLife This page is now complete - would you be able to update the schematron and close the ticket? Thanks :D

**Closed** 2020-11-25 13:56 UTC
Labels: content
