### ISSUE TITLE
Create Reference Citation page

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/schematron-gitbook#3] opened 2020-04-09 13:47 UTC
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] '[Message change](https://github.com/elifesciences/eLife-JATS-schematron/issues/new/choose)' ticket created for Fred to update the Schematron

**Comment by JGilbert-eLife** [comment] 2020-04-17 15:31
Page is drafted, will need to review again on Monday when my brain is less frazzled - but any comments welcome in the meantime!

**Comment by JGilbert-eLife** [comment] 2020-04-17 15:33
https://app.gitbook.com/@elifesciences/s/schematron/article-details/content/reference-citations

**Comment by FAtherden-eLife** [comment] 2020-04-17 16:25
What's the best way to feedback? Comments in the page (presumably creating a fork?)? Or comments in this ticket?

**Comment by FAtherden-eLife** [comment] 2020-04-17 16:36
`final-ref-xref-test-1`

> If, for example, only the year for a reference citation is present within the link ( `<xref ref-type="bibr" rid="bib16">2010</xref>`), this should be corrected to the standard citation style. However, during author proofing, the authors may request that an alternate style such as 'Smith (2010)' be used for particular reference citaitons. In the case where this has been explicitly requested, the indicated citations may be left in this alternate style and this warning can be ignored.

I think we can get rid of "this warning can be ignored.". Sorry, I definitely caused some confusion in the meeting earlier. `final-ref-xref-test-1` will only fire if the reference citation is **not** in either of the formats `Smith (2010)` and `Smith, 2010`. There's no warning at post-author for `Smith (2010)` (I thought there was [hence why I said so in the meeting] but there isn't - I can create one if it's useful but since authors aren't able to make this edit themselves it seems unnecessary?). 

So we always want this error to be heeded.

**Comment by naushinthomson** [comment] 2020-04-20 08:13
In the 'Citations that have not been converted properly' section would it be worth mentioning that sometimes numbers in square brackets are incorrectly formatted as references when they are actually scientific terms? I've seen a few instances of this recently. Or would this be more appropriate in another page entirely?

**Comment by naushinthomson** [comment] 2020-04-20 08:24
I've gone through and made some minor spelling edits in case you wonder what the last merge was! In general I think it looks good to me so far! Do we need to also add something about 'c.f.'?

**Comment by Melissa37** [comment] 2020-04-20 08:27
>There should be a space between the word that precedes the citations and the opening bracket.

I wonder whether this is needed as I had to read it twice and it's a basic grammatical issue, not house style. Or add a good and bad example?

**Comment by Melissa37** [comment] 2020-04-20 08:32
>"Pearce et al. designed a framework based on variable-order Markov models that learns statistics describing the temporal sequences in melodic sequences at various time-scales (IDyOM; Pearce, 2005; Pearce and Wiggins, 2006)."

Because the pre-editors are so literal, I wonder whether we should have a few examples here and not just this one, for example:

"Pearce et al. designed a framework based on variable-order Markov models that learns statistics describing the temporal sequences in melodic sequences at various time-scales (Pearce, 2005)."

So it's crystal clear.

**Comment by Melissa37** [comment] 2020-04-20 08:34
>Error: XXXXXX - citation does not conform to house style. It should be 'XXXXXX'. Preceding text = 'XXXXXX'.

With no context, this is confusing. Can we add a live example to replace the XXXXXXs?

**Comment by Melissa37** [comment] 2020-04-20 08:38
>final-ref-xref-test-1
Error: XXXXXX - citation does not conform to house style. It should be 'XXXXXX' or 'XXXXXX'. Preceding text = 'XXXXXX'.

I find this rather confusing, sorry!
Is the issue that "If, for example, only the year for a reference citation is present within the link ( <xref ref-type="bibr" rid="bib16">2010</xref>), " that Smith is not within the <ref> tag? If that's the case it would help to add the Smith to the text beforehand, eg:

If, for example, only the year for a reference citation is present within the link ( Smith, <xref ref-type="bibr" rid="bib16">2010</xref>),

**Comment by Melissa37** [comment] 2020-04-20 08:39
>If, for example, only the year for a reference citation is present within the link ( <xref ref-type="bibr" rid="bib16">2010</xref>), this should be corrected to the standard citation style. However, during author proofing, the authors may request that an alternate style such as 'Smith (2010)' be used for particular reference citations. In the case where this has been explicitly requested, the indicated citations may be left in this alternate style and this warning can be ignored.

I am confused by this

**Comment by Melissa37** [comment] 2020-04-20 08:42
ref-xref-test-4
Error: citation doesn't contain numbers, which must be incorrect - XXXXXX
Action: This error will fire in a reference citation does not contain any numbers, e.g. it is just 'Smith et al.,' rather than 'Smith et al., 2010'  ( <xref ref-type="bibr" rid="bib16">Smith et al.,</xref>). Correct the citation text so that both name and year are present. XXXXXX in this message will be the current, incorrect citation text.

Would be cleared if:
Action: This error will fire in a reference citation does not contain any numbers, e.g. it is just 'Smith et al.,' rather than 'Smith et al., 2010'  ( <xref ref-type="bibr" rid="bib16">Smith et al.,</xref> 2010). Correct the citation text so that both name and year are present within the <ref> tags .

**Comment by Melissa37** [comment] 2020-04-20 08:44
>ref-xref-test-5

Same issue as reported already

**Comment by Melissa37** [comment] 2020-04-20 08:53
>ref-xref-parent-test
Error: xref - XXXXXX - has a formatting parent element - XXXXXX - which is not correct.
Action: Reference citations should not be contained within style formatting such as superscript or bold (italics is an exception, see ref-xref-italic-child-test). If this formatting is present, please remove it. XXXXXX in this message will be the citation and the formatting element respectively.

I think an example would be really useful here

**Comment by Melissa37** [comment] 2020-04-20 08:53
>ref-xref-child-test
Error: xref - XXXXXX - has a formatting child element - XXXXXX - which is not correct.
Action: Reference citations should not contain style formatting such as superscript or bold (italics is an exception, see ref-xref-italic-child-test). If this formatting is present, please remove it. XXXXXX in this message will be the citation and the formatting element respectively.

Again, an example here would be really sueful

**Comment by Melissa37** [comment] 2020-04-20 08:54
>bibr-xref-target-test
Error: xref with @ref-type='XXXXXX' points to XXXXXX. This is not correct.
Action: This error will fire if a reference citation <xref> (e.g. one with the attribute ref-type="bibr") points not to some other element such as a figure. 

Can we add an example?

**Comment by FAtherden-eLife** [comment] 2020-04-20 09:32
`ref-presence` and `refs-presence`

This error will also fire in (very rare) instances where the authors use `ref` when not referring to a reference (`ref. PMID 000001` or refs. [no. for resource]). I think it would be good to include guidance on what to do in these instances as well. Since it's an error a change has to be made. Removing the full stop will fix it if it can't be re-worded.

**Comment by eLifeProduction** [comment] 2020-04-20 15:07
@Melissa37 I've addressed your comments - please could you check pre-ref-xref-test-1 + final-ref-xref-test-1 and ref-xref-test-4 + ref-xref-test-5 to see if they are clearer now? I might need to do some more revision on those as I wasn't 100% what you needed me to do!

@FAtherden-eLife I've addressed your comments.

@naushinthomson I'm in two minds about the numbers converted to references thing. Yes, we should cover it but I'm not sure *how* to cover it, since it's pretty hard to spot. I've added some text but I don't have any examples to hand.

Not sure we need to cover anything to do with c.f. I don't think we've got any rules about it?

**Comment by FAtherden-eLife** [comment] 2020-04-20 15:59
Thanks, looks good. Sorry I have a handful more final points. 
1. We have a section for "How to identify unconverted citations", but what about the inverse, like `23 Å (Smith et al., 1992)`. Do we need one on that? Or not?

2. In the `pre-ref-xref-test-1` and `final-ref-xref-test-1` sections, can we change "For example, if **the reference validator** does not correctly pick up the author names" to "For example, if **Kriya's reference validator** does not correctly pick up the author names" in order to avoid confusion?

3. `ref-xref-test-11` and `ref-xref-test-12` - is there missing code fortmatting for xml tags here - "Please note that this message may appear even when the current text is fine **(e.g. )**."

**Comment by eLifeProduction** [comment] 2020-04-20 16:04
@FAtherden-eLife 

1 - I'm unsure about this. I don't know if that belongs on this page or in the References page, along with the messages about uncited references. Any opinions welcome!

2 - put in 'proofing-system reference validator' because I don't want to have to edit it when we move to Editor!

3 - actually, I think I just plain forgot to dig out an example of this. Will fix that!

**Comment by JGilbert-eLife** [comment] 2020-04-20 16:05
@FAtherden-eLife

1 - I'm unsure about this. I don't know if that belongs on this page or in the References page, along with the messages about uncited references. Any opinions welcome!

2 - put in 'proofing-system reference validator' because I don't want to have to edit it when we move to Editor!

3 - actually, I think I just plain forgot to dig out an example of this. Will fix that!

**Comment by FAtherden-eLife** [comment] 2020-04-20 16:19
1. I've no opinion on where it should be placed, so happy for it not to be included here if thought best. 

2-3. :+1:

**Comment by bcollins14** [comment] 2020-04-21 08:52
For the following section 

"Please be aware of this issue when dealing with uncited references: the lack of citations may be caused by those the author provided not converting correctly. Additionally, the opposite problem may occur: a term that is not in fact a reference citation may be converted to one. This can occur if the author includes a superscript number or numbers in brackets." 

Can I double check if this type of error is checked by the schematron? If not, would it be worth mentioning that this should be a manual check just in case?

**Comment by Melissa37** [comment] 2020-04-21 08:55
>Error: citation is followed by ');', which in turn is followed by another link. This must be incorrect (the bracket should be removed) - 'XXXXXX'.
Action: This error will fire when a reference citation is followed by a closing parenthesis and then by a semi-colon and another citation, e.g. ". . . Smith et al., 2010); Jones et al., 2019 . . ." This should be corrected to remove the closing bracket after the first citation, leaving only the semi-colon as a separator: ". . . Smith et al., 2010; Jones et al., 2019 . . ." XXXXXX in this message will indicate the text where this error is present.

What about an instance where it might be:
....Smith et al., 2010); Jones et al., 2019 found that blah blah blah

**Comment by Melissa37** [comment] 2020-04-21 09:00
>ref-xref-test-27
Warning: citation is followed by ') (', which in turn is followed by another link - 'XXXXXX'. Should the closing and opening brackets be replaced with a '; '? i.e. 'XXXXXX'.
Action: This warning indicates that two citations (to references or assets) have been placed in two set of parentheses immediately next to each other, e.g.  “(Harrison et al, 2020) (Figure 1) ”. The two sets of parentheses should be merged and the citations should be separated with a semi-colon instead (see above). XXXXXX in this message will indicate the text that needs to be corrected and a suggestion for how to correct it, respectively.
ref-xref-test-28
Warning: citation is preceded by ') (', which in turn is preceded by another link - 'XXXXXX'. Should the closing and opening brackets be replaced with a '; '? i.e. 'XXXXXX'.
Action: This warning indicates that two citations (to references or assets) have been placed in two set of parentheses immediately next to each other, e.g.  “(Figure 1) (Harrison et al, 2020) ”. The two sets of parentheses should be merged and the citations should be separated with a semi-colon instead (see above). XXXXXX in this message will indicate the text that needs to be corrected and a suggestion for how to correct it, respectively.

and ref-xref-test-28

I don't think the explanation matches what the Schematron is doing. The Schematron is finding "citation is preceded by ') ('", it's NOT "This warning indicates that two citations (to references or assets) have been placed in two set of parentheses immediately next to each other," It could be plain text in the preceding bracket (or bracket afterwards).

I wonder whether the action should say IF the warning is fired because two citations (to references or assets) have been placed in two set of parentheses immediately next to each other then change blah blah blah.

If there preceding or following bracket contains text then a contextual decision will need to be made?

**Comment by bcollins14** [comment] 2020-04-21 09:03
bibr-xref-target-test
Error: xref with @ref-type='XXXXXX' points to XXXXXX. This is not correct.
Action: This error will fire if a reference citation <xref> (e.g. one with the attribute ref-type="bibr") points not to some other element such as a figure. So, for example, a figure citation with the type "bibr" is not allowed: <xref ref-type="bibr" rid="fig1">Figure 1</xref>. The tagging should be corrected to use the correct ref-type (ref-type="fig" in this example).

I feel this 'points not to some other element such as a figure' is a little confusing and I cannot quite understand it.

**Comment by bcollins14** [comment] 2020-04-21 09:06
> xref-bibr-presence
> Warning: Abstract contains a citation - 'XXXXXX' - which isn't usually allowed. Check that this is correct.
> Action: An article abstract should not contain any live reference citations as these cannot be rendered correctly on downstream services such as PubMed. If citations are present in the abstract, please delete them and inform the author using an author query. If these were the only citations of those references in the article (which is usually unlikely), please ask the author to add new citations for them in the main text. XXXXXX in this message will be the citation(s) in the abstract.
> 

Sorry if I have missed this, but what about when a plain text citation is needed? I cannot recall off the top of my head which article types require these.

**Comment by bcollins14** [comment] 2020-04-21 09:09
Other than my few points, I thought it was really good and easy to read :)

**Comment by Melissa37** [comment] 2020-04-21 09:14
>Warning: Abstract contains a citation - 'XXXXXX' - which isn't usually allowed. Check that this is correct.
Action: An article abstract should not contain any live reference citations as these cannot be rendered correctly on downstream services such as PubMed. If citations are present in the abstract, please delete them and inform the author using an author query. If these were the only citations of those references in the article (which is usually unlikely), please ask the author to add new citations for them in the main text. XXXXXX in this message will be the citation(s) in the abstract.

Does this also fire for DL/AR content?

**Comment by Melissa37** [comment] 2020-04-21 09:20
Thanks @JGilbert-eLife I agree with Becky that this is a great resource! Sorry about my few final finds that I missed the first time around, but I think they are relevant. Also agree with @bcollins14 that we should add something here about changing to plain text citations (do we do that anywhere except in DL/AR? I thought that was just relevant to figures/tables assets).

Cheers!!

**Comment by JGilbert-eLife** [comment] 2020-04-21 14:27
> > Warning: Abstract contains a citation - 'XXXXXX' - which isn't usually allowed. Check that this is correct.
> > Action: An article abstract should not contain any live reference citations as these cannot be rendered correctly on downstream services such as PubMed. If citations are present in the abstract, please delete them and inform the author using an author query. If these were the only citations of those references in the article (which is usually unlikely), please ask the author to add new citations for them in the main text. XXXXXX in this message will be the citation(s) in the abstract.
> 
> Does this also fire for DL/AR content?

It does not! D/Rs are excluded from all this since we are not expecting live citations there. Is that worth mentioning here or should we keep that for the sub-article page(s)?

**Comment by FAtherden-eLife** [comment] 2020-04-21 14:32
@Melissa37, @JGilbert-eLife 
>> Error: citation is followed by ');', which in turn is followed by another link. This must be incorrect (the bracket should be removed) - 'XXXXXX'.
Action: This error will fire when a reference citation is followed by a closing parenthesis and then by a semi-colon and another citation, e.g. ". . . Smith et al., 2010); Jones et al., 2019 . . ." This should be corrected to remove the closing bracket after the first citation, leaving only the semi-colon as a separator: ". . . Smith et al., 2010; Jones et al., 2019 . . ." XXXXXX in this message will indicate the text where this error is present.

>What about an instance where it might be:
>....Smith et al., 2010); Jones et al., 2019 found that blah blah blah 

I'm not aware that we've ever come across that. I can downgrade the test to a warning but it could mean that Exeter are slightly less attentive at correcting this issue if it isn't an error (obviously in an ideal world they wouldn't ignore any warning). 

What are your thoughts?

**Comment by JGilbert-eLife** [comment] 2020-04-21 14:48
I think the more likely scenario would be "Following something something (Smith et al., 2010), Jones et al., 2019 found . . ." and I agree that we don't want Exeter overlooking things.

However, at the same time, it's not impossible for a semi-colon to be used in the manner that  @Melissa37 suggests.

**Comment by Melissa37** [comment] 2020-04-21 14:54
> It does not! D/Rs are excluded from all this since we are not expecting live citations there. Is that worth mentioning here or should we keep that for the sub-article page(s)?

I think we should so there is no ambiguity

>However, at the same time, it's not impossible for a semi-colon to be used in the manner that @Melissa37 suggests.

OK, so let's ignore my initial suggestion if it's near impossible a situation :-)

**Comment by JGilbert-eLife** [comment] 2020-04-21 15:03
Ok! I have added a couple of sentences to the 'what needs to be checked' section, and I think that means I've made all the required edits. :)

**Closed** 2020-05-04 09:47 UTC
Labels: content
